version: '3'

services:
###> doctrine/doctrine-bundle ###


    database:
        image: postgres:${POSTGRES_VERSION:-14}-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-clark}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
            POSTGRES_USER: ${POSTGRES_USER:-root}
        volumes:
            - ./.docker/.pgsql-data:/var/lib/pgsql/data:rw,delegated
        ports:
            - "5432:5432"
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
