version: '3'

services:
###> doctrine/doctrine-bundle ###
#  database:
#    image: postgres:${POSTGRES_VERSION:-14}-alpine
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB:-clark}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
#      POSTGRES_USER: ${POSTGRES_USER:-root}
#    volumes:
#      - db-data:/var/lib/postgresql/data:rw
    database:
      image: postgres:${POSTGRES_VERSION:-14}-alpine
      environment:
        POSTGRES_DB: ${POSTGRES_DB:-clark}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
        POSTGRES_USER: ${POSTGRES_USER:-root}
      volumes:
            - db-data:/var/lib/postgresql/data:rw
      ports:
        - "5432:5432"
#      networks:
#        - internal
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
